/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ClsDataHora;
import controle.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modeloBeans.BeansTexte;
import modeloBeans.BeansUsuario;
import modeloConection.ConexaoBD;
import modeloDAO.DaoTexte;
import modeloDAO.DaoUsuario;

/**
 *
 * @author Gustavo
 */
public class TelaPonteamento extends javax.swing.JFrame {
    ClsDataHora objDataHora = new ClsDataHora();
    ConexaoBD con = new ConexaoBD();
    DaoUsuario contUsu = new DaoUsuario();
    BeansUsuario modusu = new BeansUsuario();
    DaoTexte dao = new DaoTexte();
    BeansTexte test = new BeansTexte();
    public TelaPonteamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPreccp1 = new javax.swing.JButton();
        jButtonPreccp2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ponteamento");

        jButtonPreccp1.setText("add");
        jButtonPreccp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreccp1ActionPerformed(evt);
            }
        });

        jButtonPreccp2.setText("Voltar");
        jButtonPreccp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreccp2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonPreccp2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPreccp1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPreccp1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 275, Short.MAX_VALUE)
                        .addComponent(jButtonPreccp2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(732, 355));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPreccp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreccp1ActionPerformed
            
        test.setPreccp(Integer.parseInt(jTextField1.getText()));
        dao.SalvarPrec(test);
        
        
       // preenchertab("select  a.pont_data, l.hora_login, a.pont_horalocal, a.pont_justificativa from apontamento as a inner join login as l on a.cod_apon = l.login_codapon where cod_apon =cod_apon");
        
        
        /*  if (modusu.getHora() >= modusu.getHoraLimite1() && modusu.getHora() <= modusu.getHoraLimite2()) {
         modusu.setPosto(jTextFieldPosto.getText());
         modusu.setPreccp(Integer.parseInt(jTextFieldprec.getText()));
         modusu.setNomeUsu(jTextFieldNome.getText());
         //modusu.setHoraLimite1(Integer.parseInt(jTextFieldHora1.getText()));
         //modusu.setHoraLimite2(Integer.parseInt(jTextFieldHora2.getText()));
         modusu.setHora(Integer.parseInt(jTextFieldHoralocal.getText()));
         modusu.setJustificativa(jTextFieldJustificativa.getText());
         contUsu.Pontear(modusu);  
         JOptionPane.showMessageDialog(null, "Ponteamendo realizado com sucesso!");
              }   
        else{
            JOptionPane.showMessageDialog(null, "O horario de ponteamento foi ultrapassado, justifique seu atraso!");
            jTextFieldJustificativa.setEnabled(true);
           modusu.setPreccp(jTextFieldPreccp.getText());
            contUsu.Pontear(modusu);*/
        
    }//GEN-LAST:event_jButtonPreccp1ActionPerformed
public void preenchertab(String Sql){
    /*    ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Data", "Hora Login", "Hora Apontada", "Justificativa"};
        con.conexao();
        con.executaSql(Sql);

        try {
            con.rs.first();
            do {
                dados.add(new Object[]{con.rs.getString("pont_data"), con.rs.getString("hora_log"), con.rs.getString("pont_horalocal"), con.rs.getString("pont_justificativa")});

            } while (con.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayList!!" + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        jTable1.setModel(modelo);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(92);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(3).setResizable(false);*/
    }
    private void jButtonPreccp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreccp2ActionPerformed
         TelaPrincipal telaPrin = new TelaPrincipal();
        telaPrin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonPreccp2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPonteamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPonteamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPonteamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPonteamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPonteamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPreccp1;
    private javax.swing.JButton jButtonPreccp2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
