/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.ApontamentoLogin;
import modeloBeans.BeansUsuario;
import modeloConection.ConexaoBD;
import modeloDAO.DaoApontamentoLogin;
import modeloDAO.DaoUsuario;

/**
 *
 * @author Gustavo
 */
public class TelaControleUsuario extends javax.swing.JFrame {

    ConexaoBD con = new ConexaoBD();
    DaoUsuario contUsu = new DaoUsuario();
    BeansUsuario modusu = new BeansUsuario();
    int flag = 0;

    public TelaControleUsuario() {
        initComponents();
        //   con.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jTextFieldNomeCad = new javax.swing.JTextField();
        jTextFieldPreccpCad = new javax.swing.JTextField();
        jComboBoxPosto = new javax.swing.JComboBox<String>();
        jComboBoxSexo = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSetorCad = new javax.swing.JTextField();
        jTextFieldSenhaCad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jTextFieldHoraLimite1 = new javax.swing.JTextField();
        jTextFieldHoraLimite2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonPesquisarNome = new javax.swing.JButton();
        jTextFieldPesquisar1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonDeletar1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextFieldDgtFamiliar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonNome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jButtonPRECCP = new javax.swing.JButton();
        jButtonSetor = new javax.swing.JButton();
        jLabelFundoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CDU");
        getContentPane().setLayout(null);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setToolTipText("");

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jTextFieldNomeCad.setEnabled(false);
        jTextFieldNomeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCadActionPerformed(evt);
            }
        });

        jTextFieldPreccpCad.setEnabled(false);

        jComboBoxPosto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SD", "CB", "SGT", "ST", "ASP OF", "TEN", "CAP", "MAJ", "TEN CEL", "CEL" }));
        jComboBoxPosto.setEnabled(false);
        jComboBoxPosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPostoActionPerformed(evt);
            }
        });

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        jComboBoxSexo.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Posto:");

        jTextFieldSetorCad.setEnabled(false);

        jTextFieldSenhaCad.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Senha:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Setor:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("PREC-CP:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome Completo:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Sexo:");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonDeletar.setText("Deletar");
        jButtonDeletar.setEnabled(false);
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar por PREC-CP");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jTextFieldPesquisar.setName("Digite o PRECCP"); // NOI18N

        jTextFieldHoraLimite1.setEnabled(false);

        jTextFieldHoraLimite2.setEnabled(false);
        jTextFieldHoraLimite2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoraLimite2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Hora Limite:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("até");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("De");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonPesquisarNome.setText("Pesquisar por Nome");
        jButtonPesquisarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarNomeActionPerformed(evt);
            }
        });

        jTextFieldPesquisar1.setName("Digite o PRECCP"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Posto:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Sexo:");

        jButtonDeletar1.setText("Limpar");
        jButtonDeletar1.setEnabled(false);
        jButtonDeletar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletar1ActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldDgtFamiliar.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonCancelar)
                                            .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonDeletar1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel10)
                                                .addGap(10, 10, 10)
                                                .addComponent(jTextFieldHoraLimite1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel9)
                                                .addGap(10, 10, 10)
                                                .addComponent(jTextFieldHoraLimite2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3)
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldSetorCad)
                                            .addComponent(jTextFieldSenhaCad)
                                            .addComponent(jTextFieldPreccpCad, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldDgtFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxPosto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPesquisarNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNovo)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jButtonSalvar))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldPreccpCad)
                                .addComponent(jTextFieldDgtFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(jTextFieldSenhaCad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jTextFieldSetorCad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextFieldHoraLimite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextFieldHoraLimite2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDeletar1)
                                .addGap(3, 3, 3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButtonCancelar)
                                        .addGap(6, 6, 6)
                                        .addComponent(jButtonEditar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel7)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxPosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addComponent(jButtonDeletar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisarNome)
                    .addComponent(jTextFieldPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );

        jTextFieldPesquisar.getAccessibleContext().setAccessibleName("");
        jTextFieldPesquisar.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("Controle do Usuario", jPanel1);

        jButtonNome.setText("Nome");
        jButtonNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNomeActionPerformed(evt);
            }
        });

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableUsuarios);

        jButtonPRECCP.setText("PREC-CP");
        jButtonPRECCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPRECCPActionPerformed(evt);
            }
        });

        jButtonSetor.setText("Setor");
        jButtonSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonNome, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPRECCP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPRECCP, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pesquisar All", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 130, 640, 340);

        jLabelFundoPrincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CDU.png"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 0, 660, 510);

        setSize(new java.awt.Dimension(678, 543));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldNomeCad.setEnabled(true);
        jTextFieldPreccpCad.setEnabled(true);
        jTextFieldSenhaCad.setEnabled(true);
        jTextFieldSetorCad.setEnabled(true);
        jComboBoxPosto.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonDeletar.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldHoraLimite1.setEnabled(true);
        jTextFieldHoraLimite2.setEnabled(true);
        jButtonDeletar1.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jTextFieldNomeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCadActionPerformed

    }//GEN-LAST:event_jTextFieldNomeCadActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
       /* if (flag == 1) {
            if (jTextFieldPreccpCad.getText().length() != 11) {
                JOptionPane.showMessageDialog(null, "O PREC-CP deve ter 11 caracteres.");
            } else {
                modusu.setPreccp(jTextFieldPreccpCad.getText());
                modusu.setSenha(jTextFieldSenhaCad.getText());
                modusu.setNomeUsu(jTextFieldNomeCad.getText());
                modusu.setSetor(jTextFieldSetorCad.getText());
                modusu.setSexo((String) jComboBoxSexo.getSelectedItem());
                modusu.setPosto((String) jComboBoxPosto.getSelectedItem());
                modusu.setHoraLimite1(Integer.parseInt(jTextFieldHoraLimite1.getText()));
                modusu.setHoraLimite2(Integer.parseInt(jTextFieldHoraLimite2.getText()));
                contUsu.Salvar(modusu);
            }
        } else {
            modusu.setPreccp(jTextFieldPreccpCad.getText());
            modusu.setSenha(jTextFieldSenhaCad.getText());
            modusu.setNomeUsu(jTextFieldNomeCad.getText());
            modusu.setSetor(jTextFieldSetorCad.getText());
            modusu.setSexo((String) jComboBoxSexo.getSelectedItem());
            modusu.setPosto((String) jComboBoxPosto.getSelectedItem());
            modusu.setHoraLimite1(Integer.parseInt(jTextFieldHoraLimite1.getText()));
            modusu.setHoraLimite2(Integer.parseInt(jTextFieldHoraLimite2.getText()));
            contUsu.Editar(modusu);
            jTextFieldNomeCad.setEnabled(false);
            jTextFieldPreccpCad.setEnabled(false);
            jTextFieldSenhaCad.setEnabled(false);
            jTextFieldSetorCad.setEnabled(false);
            jComboBoxPosto.setEnabled(false);
            jComboBoxSexo.setEnabled(false);
            jTextFieldHoraLimite1.setEnabled(false);
            jTextFieldHoraLimite2.setEnabled(false);
        }*/
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag = 2;
        jTextFieldNomeCad.setEnabled(true);
        jTextFieldPreccpCad.setEnabled(true);
        jTextFieldSenhaCad.setEnabled(true);
        jTextFieldSetorCad.setEnabled(true);
        jTextFieldHoraLimite1.setEnabled(true);
        jTextFieldHoraLimite2.setEnabled(true);
        jComboBoxPosto.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonDeletar.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir o usuario?");
       /* if (resposta == JOptionPane.YES_OPTION) {
            modusu.setPreccp(jTextFieldPreccpCad.getText());
            jTextFieldPreccpCad.setText("");
            jTextFieldSenhaCad.setText("");
            jTextFieldNomeCad.setText("");
            jTextFieldSetorCad.setText("");
            jTextFieldHoraLimite1.setText("");
            jTextFieldHoraLimite2.setText("");
            jTextFieldPesquisar.setText("");
            contUsu.Excluir(modusu);
        } else {

        }*/
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
/*        modusu.setPesquisa(jTextFieldPesquisar.getText());
        BeansUsuario model = contUsu.buscarUsuario(modusu);
        jTextFieldPreccpCad.setText(String.valueOf(model.getPreccp()));
        jTextFieldSenhaCad.setText(model.getSenha());
        jTextFieldNomeCad.setText(model.getNomeUsu());
        jTextFieldSetorCad.setText(model.getSetor());
        jTextFieldHoraLimite1.setText(String.valueOf(model.getHoraLimite1()));
        jTextFieldHoraLimite2.setText(String.valueOf(model.getHoraLimite2()));
        jComboBoxSexo.setSelectedItem(model.getSexo());
        jComboBoxPosto.setSelectedItem(model.getPosto());
        jButtonEditar.setEnabled(true);
        jButtonDeletar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jTextFieldNomeCad.setEnabled(false);
        jTextFieldPreccpCad.setEnabled(false);
        jTextFieldSenhaCad.setEnabled(false);
        jTextFieldSetorCad.setEnabled(false);
        jComboBoxPosto.setEnabled(false);
        jComboBoxSexo.setEnabled(false);*/
        DaoApontamentoLogin dao = new DaoApontamentoLogin();
        ApontamentoLogin ap = new ApontamentoLogin();
        jTextFieldPreccpCad.setText(ap.getDataAponLog());
        jTextFieldSenhaCad.setText(String.valueOf(ap.getHoraLog()));
        jTextFieldSenhaCad.setText(String.valueOf(ap.getHoraApont()));
        jTextFieldPreccpCad.setText(ap.getJustificativaApont());
        dao.buscarUsua(ap);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldHoraLimite2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoraLimite2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoraLimite2ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        jTextFieldNomeCad.setEnabled(!true);
        jTextFieldPreccpCad.setEnabled(!true);
        jTextFieldSenhaCad.setEnabled(!true);
        jTextFieldSetorCad.setEnabled(!true);
        jTextFieldHoraLimite1.setEnabled(!true);
        jTextFieldHoraLimite2.setEnabled(!true);
        jComboBoxPosto.setEnabled(!true);
        jComboBoxSexo.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonDeletar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBoxPostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPostoActionPerformed

    private void jButtonNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNomeActionPerformed
        preencherTabela("SELECT*FROM usuario order by nome_usu");
    }//GEN-LAST:event_jButtonNomeActionPerformed

    private void jButtonPRECCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPRECCPActionPerformed
        preencherTabela("SELECT*FROM usuario order by preccp");
    }//GEN-LAST:event_jButtonPRECCPActionPerformed

    private void jButtonSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetorActionPerformed
        preencherTabela("SELECT*FROM usuario order by setor_usu");
    }//GEN-LAST:event_jButtonSetorActionPerformed

    private void jButtonPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarNomeActionPerformed
        modusu.setPesquisar(jTextFieldPesquisar1.getText());
        BeansUsuario model = contUsu.buscarUsuario(modusu);
        jTextFieldPreccpCad.setText(String.valueOf(model.getPreccp()));
        jTextFieldSenhaCad.setText(model.getSenha());
        jTextFieldNomeCad.setText(model.getNome());
        jTextFieldSetorCad.setText(model.getSetor());
        jComboBoxSexo.setSelectedItem(model.getSexo());
        jComboBoxPosto.setSelectedItem(model.getPosto());
        jTextFieldHoraLimite1.setText(String.valueOf(model.getHoraEntrada()));
        jTextFieldHoraLimite2.setText(String.valueOf(model.getHoraSaida()));
        jTextFieldDgtFamiliar.setText(model.getDgtFamiliar());
        jButtonEditar.setEnabled(true);
        jButtonDeletar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jTextFieldNomeCad.setEnabled(false);
        jTextFieldPreccpCad.setEnabled(false);
        jTextFieldSenhaCad.setEnabled(false);
        jTextFieldSetorCad.setEnabled(false);
        jComboBoxPosto.setEnabled(false);
        jComboBoxSexo.setEnabled(false);
    }//GEN-LAST:event_jButtonPesquisarNomeActionPerformed

    private void jButtonDeletar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletar1ActionPerformed
        jTextFieldPreccpCad.setText("");
            jTextFieldSenhaCad.setText("");
            jTextFieldNomeCad.setText("");
            jTextFieldSetorCad.setText("");
            jTextFieldHoraLimite1.setText("");
            jTextFieldHoraLimite2.setText("");
            jTextFieldPesquisar.setText("");
    }//GEN-LAST:event_jButtonDeletar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Posto", "Nome", "PREC-CP", "Setor", "Sexo", "Hora inicial", "Hora Limite"};
        con.conexao();
        con.executaSql(Sql);

        try {
            con.rs.first();
            do {
                dados.add(new Object[]{con.rs.getString("posto_usu"), con.rs.getString("nome_usu"), con.rs.getString("preccp"), con.rs.getString("setor_usu"), con.rs.getString("sexo_usu"), con.rs.getString("horalimite_usu"), con.rs.getString("horalimite2_usu")});

            } while (con.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayList!!" + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        jTableUsuarios.setModel(modelo);
        jTableUsuarios.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableUsuarios.getColumnModel().getColumn(0).setResizable(false);
        jTableUsuarios.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTableUsuarios.getColumnModel().getColumn(1).setResizable(false);
        jTableUsuarios.getColumnModel().getColumn(2).setPreferredWidth(92);
        jTableUsuarios.getColumnModel().getColumn(2).setResizable(false);
        jTableUsuarios.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTableUsuarios.getColumnModel().getColumn(3).setResizable(false);
        jTableUsuarios.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTableUsuarios.getColumnModel().getColumn(4).setResizable(false);
        jTableUsuarios.getColumnModel().getColumn(5).setPreferredWidth(80);
        jTableUsuarios.getColumnModel().getColumn(5).setResizable(false);
        jTableUsuarios.getColumnModel().getColumn(6).setPreferredWidth(80);
        jTableUsuarios.getColumnModel().getColumn(6).setResizable(false);
        jTableUsuarios.getTableHeader().setReorderingAllowed(false);
        jTableUsuarios.setAutoResizeMode(jTableUsuarios.AUTO_RESIZE_OFF);
        jTableUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaControleUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaControleUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaControleUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaControleUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaControleUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonDeletar1;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonNome;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPRECCP;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisarNome;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonSetor;
    private javax.swing.JComboBox<String> jComboBoxPosto;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JTextField jTextFieldDgtFamiliar;
    private javax.swing.JTextField jTextFieldHoraLimite1;
    private javax.swing.JTextField jTextFieldHoraLimite2;
    private javax.swing.JTextField jTextFieldNomeCad;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldPesquisar1;
    private javax.swing.JTextField jTextFieldPreccpCad;
    private javax.swing.JTextField jTextFieldSenhaCad;
    private javax.swing.JTextField jTextFieldSetorCad;
    // End of variables declaration//GEN-END:variables
}
