/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.sun.javafx.font.FontFactory;
import controle.ClsDataHora;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.text.Document;
import modeloBeans.ApontamentoLogin;
import modeloBeans.BeansApontamento;
import modeloBeans.BeansUsuario;
import modeloConection.ConexaoBD;
import modeloDAO.DaoApontamento;
import modeloDAO.DaoApontamentoLogin;
import modeloDAO.DaoUsuario;

/**
 *
 * @author Gustavo
 */
public class TelaPrincipal extends javax.swing.JFrame {
        ClsDataHora objDataHora = new ClsDataHora();
        ConexaoBD conecta = new ConexaoBD();
        DaoUsuario contUsu = new DaoUsuario();
        BeansUsuario modusu = new BeansUsuario();
        BeansApontamento apont = new BeansApontamento();
        DaoApontamento daoapont = new DaoApontamento();
        ApontamentoLogin apolog = new ApontamentoLogin();
        DaoApontamentoLogin daoapontlog = new DaoApontamentoLogin();
        Relatorio enviatext;

    /**
     * Creates new form TelaPrincipal
     */ public void recebendo(Integer recebe){
        jTextFieldPreccpCad2.setText(recebe.toString());
        jTextFieldPreccp.setText(recebe.toString());
        jTextFieldRelatorio.setText(recebe.toString());
    }
        
    public TelaPrincipal() {
        conecta.conexao();
        initComponents();
        
       
        
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldHora3 = new javax.swing.JTextField();
        jTextFieldhora2 = new javax.swing.JTextField();
        jButtonRelatorio2 = new javax.swing.JButton();
        jButtonRelatorio = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonPreccp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTextFieldPreccp = new javax.swing.JTextField();
        jTextFieldPreccpCad2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        javax.swing.JTabbedPane jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldJustificativa = new javax.swing.JTextField();
        jTextFieldHora1 = new javax.swing.JTextField();
        jTextFieldHora2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldprec = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPostousu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNomeusu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldHoralocalusu = new javax.swing.JTextField();
        jTextFieldDatausu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonPreccp1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldHoraSaida = new javax.swing.JTextField();
        jTextFieldDgtfam = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextFieldRelatorio = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldNomeCad = new javax.swing.JTextField();
        jTextFieldDgtfamiliar = new javax.swing.JTextField();
        jComboBoxPostocad = new javax.swing.JComboBox<String>();
        jTextFieldSetorCad = new javax.swing.JTextField();
        jTextFieldSenhaCad = new javax.swing.JTextField();
        jButtonCadasdro = new javax.swing.JButton();
        jComboBoxSexocad = new javax.swing.JComboBox<String>();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldHoraLimite1 = new javax.swing.JTextField();
        jTextFieldHoraLimite2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldPreccpCad1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemADM = new javax.swing.JMenuItem();

        jTextFieldHora3.setText("0000");

        jTextFieldhora2.setText("0000");

        jButtonRelatorio2.setFont(new java.awt.Font("Impact", 0, 11)); // NOI18N
        jButtonRelatorio2.setText("Menu");
        jButtonRelatorio2.setToolTipText("Relatorio");
        jButtonRelatorio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorio2ActionPerformed(evt);
            }
        });

        jButtonRelatorio.setFont(new java.awt.Font("Impact", 0, 11)); // NOI18N
        jButtonRelatorio.setText("Relatorio");
        jButtonRelatorio.setToolTipText("Relatorio");
        jButtonRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Nome:");

        jLabel14.setText("PREC-CP:");

        jButton1.setText("Pesquisar Usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonPreccp.setText("Executar");
        jButtonPreccp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreccpActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel5);
        jLabel5.setBounds(478, 23, 0, 0);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Continuar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton6);
        jButton6.setBounds(150, 130, 120, 30);
        jInternalFrame1.getContentPane().add(jTextFieldPreccp);
        jTextFieldPreccp.setBounds(230, 130, 25, 20);
        jInternalFrame1.getContentPane().add(jTextFieldPreccpCad2);
        jTextFieldPreccpCad2.setBounds(180, 130, 25, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Não repasse sua senha para niguém!");
        jInternalFrame1.getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 80, 390, 22);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setText("ATENÇÃO");
        jInternalFrame1.getContentPane().add(jLabel29);
        jLabel29.setBounds(160, 10, 120, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("Evite efetuar mais de um Apontamento por dia!");
        jInternalFrame1.getContentPane().add(jLabel30);
        jLabel30.setBounds(10, 50, 390, 22);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(160, 130, 450, 210);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setRequestFocusEnabled(false);

        jPanel2.setBackground(new java.awt.Color(214, 217, 223));
        jPanel2.setToolTipText("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TextoFundocinza.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("          Tela Inicial          ", jPanel2);

        jTextFieldJustificativa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldJustificativa.setText("N/A.");
        jTextFieldJustificativa.setEnabled(false);
        jTextFieldJustificativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJustificativaActionPerformed(evt);
            }
        });

        jTextFieldHora1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldHora1.setEnabled(false);
        jTextFieldHora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHora1ActionPerformed(evt);
            }
        });

        jTextFieldHora2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldHora2.setEnabled(false);
        jTextFieldHora2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHora2ActionPerformed(evt);
            }
        });

        jLabel6.setText("PREC-CP");

        jTextFieldprec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldprec.setEnabled(false);
        jTextFieldprec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldprecActionPerformed(evt);
            }
        });

        jLabel3.setText("Posto:");

        jTextFieldPostousu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPostousu.setEnabled(false);
        jTextFieldPostousu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPostousuActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome:");

        jTextFieldNomeusu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNomeusu.setEnabled(false);
        jTextFieldNomeusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeusuActionPerformed(evt);
            }
        });

        jLabel10.setText("Hora local:");

        jLabel9.setText("Data local:");

        jTextFieldHoralocalusu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldHoralocalusu.setEnabled(false);
        jTextFieldHoralocalusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoralocalusuActionPerformed(evt);
            }
        });

        jTextFieldDatausu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDatausu.setEnabled(false);
        jTextFieldDatausu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDatausuActionPerformed(evt);
            }
        });

        jLabel8.setText("Justificativa de atraso:");

        jButtonPreccp1.setText("Efetuar Ponteamento");
        jButtonPreccp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreccp1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Hora Limite");

        jLabel12.setText("Saida:");

        jLabel13.setText("Entrada:");

        jButton4.setText("Sair");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel31.setText("Hora Saida:");

        jTextFieldHoraSaida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldHoraSaida.setEnabled(false);
        jTextFieldHoraSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoraSaidaActionPerformed(evt);
            }
        });

        jTextFieldDgtfam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDgtfam.setEnabled(false);
        jTextFieldDgtfam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDgtfamActionPerformed(evt);
            }
        });

        jLabel32.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPostousu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextFieldNomeusu, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFieldprec, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDgtfam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDatausu, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHoralocalusu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHoraSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldJustificativa)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jButtonPreccp1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDatausu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHoralocalusu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel31)
                    .addComponent(jTextFieldHoraSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPostousu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeusu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldprec, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDgtfam, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldJustificativa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButtonPreccp1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("          Apontamento         ", jPanel3);

        jLabel23.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel23.setText("Como deseja visualizar seus apontamentos ?");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Ver agora:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Download PDF:");

        jButton2.setText("Visualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Download");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216)
                        .addComponent(jTextFieldRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("           Relatorio de Apontamentos          ", jPanel4);

        jPanel5.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(244, 244, 244));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Nome Completo:");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(12, 13, 104, 17);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Até:");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(340, 70, 30, 17);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Posto:");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(10, 170, 40, 17);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Setor:");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(10, 90, 38, 17);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Senha:");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(10, 130, 43, 17);

        jTextFieldNomeCad.setEnabled(false);
        jTextFieldNomeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCadActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldNomeCad);
        jTextFieldNomeCad.setBounds(120, 13, 428, 30);

        jTextFieldDgtfamiliar.setEnabled(false);
        jPanel6.add(jTextFieldDgtfamiliar);
        jTextFieldDgtfamiliar.setBounds(160, 50, 20, 30);

        jComboBoxPostocad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SD", "CB", "SGT", "ST", "ASP OF", "TEN", "CAP", "MAJ", "TEN CEL", "CEL" }));
        jComboBoxPostocad.setEnabled(false);
        jPanel6.add(jComboBoxPostocad);
        jComboBoxPostocad.setBounds(70, 170, 145, 30);

        jTextFieldSetorCad.setEnabled(false);
        jPanel6.add(jTextFieldSetorCad);
        jTextFieldSetorCad.setBounds(70, 90, 146, 30);

        jTextFieldSenhaCad.setEnabled(false);
        jPanel6.add(jTextFieldSenhaCad);
        jTextFieldSenhaCad.setBounds(70, 130, 146, 30);

        jButtonCadasdro.setText("Alterar");
        jButtonCadasdro.setEnabled(false);
        jButtonCadasdro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadasdroActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonCadasdro);
        jButtonCadasdro.setBounds(350, 170, 139, 49);

        jComboBoxSexocad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        jComboBoxSexocad.setEnabled(false);
        jPanel6.add(jComboBoxSexocad);
        jComboBoxSexocad.setBounds(70, 210, 145, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Sexo:");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(10, 210, 36, 17);

        jTextFieldHoraLimite1.setEnabled(false);
        jPanel6.add(jTextFieldHoraLimite1);
        jTextFieldHoraLimite1.setBounds(260, 70, 68, 30);

        jTextFieldHoraLimite2.setEnabled(false);
        jTextFieldHoraLimite2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoraLimite2ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextFieldHoraLimite2);
        jTextFieldHoraLimite2.setBounds(370, 70, 68, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("-");
        jPanel6.add(jLabel26);
        jLabel26.setBounds(147, 60, 40, 10);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Horario de Apontamento:");
        jPanel6.add(jLabel27);
        jLabel27.setBounds(230, 50, 160, 17);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("De:");
        jPanel6.add(jLabel28);
        jLabel28.setBounds(230, 70, 30, 17);

        jTextFieldPreccpCad1.setEnabled(false);
        jPanel6.add(jTextFieldPreccpCad1);
        jTextFieldPreccpCad1.setBounds(70, 50, 70, 30);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Preccp:");
        jPanel6.add(jLabel33);
        jLabel33.setBounds(10, 50, 47, 17);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(10, 62, 574, 247);

        jLabel21.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel21.setText("Alterar dados pessoais");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(10, 11, 221, 40);

        jTabbedPane1.addTab("         Área do Usuario          ", jPanel5);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 140, 740, 390);

        jLabelFundoPrincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/capaprincipal.png"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 0, 760, 600);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 452, 402);

        jMenu2.setText("Área do Administrador");

        jMenuItemADM.setText("Controle do Usuario");
        jMenuItemADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemADMActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemADM);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(772, 652));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemADMActionPerformed
        TelaLoginAdm telaLog = new TelaLoginAdm();
        telaLog.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemADMActionPerformed

    private void jButtonRelatorio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorio2ActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRelatorio2ActionPerformed

    private void jButtonRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioActionPerformed
        Relatorio rela = new Relatorio();
        rela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRelatorioActionPerformed

    private void jTextFieldJustificativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJustificativaActionPerformed
        // TODO add your hadling code here:
    }//GEN-LAST:event_jTextFieldJustificativaActionPerformed

    private void jTextFieldHora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHora1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHora1ActionPerformed

    private void jTextFieldHora2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHora2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHora2ActionPerformed

    private void jTextFieldprecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldprecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldprecActionPerformed

    private void jTextFieldPostousuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPostousuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPostousuActionPerformed

    private void jTextFieldNomeusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeusuActionPerformed

    private void jTextFieldHoralocalusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoralocalusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoralocalusuActionPerformed

    private void jTextFieldDatausuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDatausuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDatausuActionPerformed

    private void jButtonPreccp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreccp1ActionPerformed
   /*
            modusu.setPosto(jTextFieldPostousu.getText());
            modusu.setPreccp(jTextFieldprec.getText());
            modusu.setNomeUsu(jTextFieldNomeusu.getText());
            modusu.setHoraLimite1(Integer.parseInt(jTextFieldHora1.getText()));
            modusu.setHoraLimite2(Integer.parseInt(jTextFieldHora2.getText()));
            modusu.setHora(Integer.parseInt(jTextFieldHoralocalusu.getText()));
            modusu.setJustificativa(jTextFieldJustificativa.getText());
            contUsu.Pontear(modusu);
            JOptionPane.showMessageDialog(null, "Ponteamendo realizado com sucesso!");  */                                         
    }//GEN-LAST:event_jButtonPreccp1ActionPerformed

    private void jButtonPreccpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreccpActionPerformed
        
    }//GEN-LAST:event_jButtonPreccpActionPerformed

    private void jTextFieldNomeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeCadActionPerformed

    private void jButtonCadasdroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadasdroActionPerformed
        modusu.setPreccp(Integer.parseInt(jTextFieldDgtfamiliar.getText()));
        modusu.setSenha(jTextFieldSenhaCad.getText());
        modusu.setNome(jTextFieldNomeCad.getText());
        modusu.setSetor(jTextFieldSetorCad.getText());
        modusu.setSexo((String) jComboBoxSexocad.getSelectedItem());
        modusu.setPosto((String) jComboBoxPostocad.getSelectedItem());
        modusu.setHoraEntrada(Integer.parseInt(jTextFieldHora1.getText()));
        modusu.setHoraSaida(Integer.parseInt(jTextFieldHora1.getText()));
        modusu.setDgtFamiliar(jTextFieldDgtfamiliar.getText());
        contUsu.Editar(modusu);  
        int resposta =0;
       // resposta = JOptionPane.showMessageDialog(null, "Por favor, faça o logoff e entre com seu login e senha novamente.");
        JOptionPane.showMessageDialog(null, "Por favor, faça o logoff e entre com seu login e senha novamente.");
        
    }//GEN-LAST:event_jButtonCadasdroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldHoraLimite2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoraLimite2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoraLimite2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           /* jTextFieldHoralocalusu.setText(objDataHora.MostraHora());
            apont.setPontpostousu(jTextFieldPostousu.getText());
            apont.setPontnomeusu(jTextFieldNomeusu.getText());
            apont.setPontpreccpusu(jTextFieldprec.getText());
            apont.setPonthora(Integer.parseInt(jTextFieldHora1.getText()));
            apont.setPonthoralocal(Integer.parseInt(jTextFieldHoralocalusu.getText()));
            apont.setPontdata(jTextFieldDatausu.getText());
            apont.setPontjustificativa(jTextFieldJustificativa.getText());
            apont.setPonthora2(Integer.parseInt(jTextFieldHora2.getText()));
            daoapont.Salvar(apont);*/
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //////////////////////tela do apontamento///////////////
        modusu.setPesquisar(jTextFieldprec.getText());
      BeansUsuario model = contUsu.buscarUsuario(modusu);
      jTextFieldDgtfamiliar.setText(String.valueOf(model.getPreccp()));
      jTextFieldSenhaCad.setText(model.getSenha());
      jTextFieldNomeCad.setText(model.getNome());
      jTextFieldSetorCad.setText(model.getSetor());
      jComboBoxSexocad.setSelectedItem(model.getSexo());
      jComboBoxPostocad.setSelectedItem(model.getPosto());
      jTextFieldHoraLimite1.setText(String.valueOf(model.getHoraEntrada()));
      jTextFieldHoraLimite2.setText(String.valueOf(model.getHoraSaida()));
      jTextFieldDgtfam.setText(model.getDgtFamiliar());
        jTextFieldNomeCad.setEnabled(true);
        jTextFieldDgtfamiliar.setEnabled(true);
        jTextFieldSenhaCad.setEnabled(true);
        jTextFieldSetorCad.setEnabled(true);
        jComboBoxPostocad.setEnabled(true);
        jComboBoxSexocad.setEnabled(true);
        jButtonCadasdro.setEnabled(true);
        jInternalFrame1.dispose();
        ///////////////////////Tela de Editar do Usuario//////////////////////////////
        modusu.setPesquisar(jTextFieldprec.getText());      
        jTextFieldprec.setText(String.valueOf(model.getPreccp()));        
        jTextFieldNomeusu.setText(model.getNome());       
        jTextFieldPostousu.setText(model.getPosto());
        jTextFieldHora1.setText(String.valueOf(model.getHoraEntrada()));
       jTextFieldHora2.setText(String.valueOf(model.getHoraSaida()));
        jTextFieldDatausu.setText(objDataHora.MostraData());
        jTextFieldHoralocalusu.setText(objDataHora.MostraHora());
        jTextFieldDgtfamiliar.setText(model.getDgtFamiliar());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 String PDF = "Apontamento.pdf";
        Document documentoPDF = new Document();
        try {
            //criar uma instancia do documento
            PdfWriter.getInstance(documentoPDF, new FileOutputStream(PDF));
             //abrir o documento
            documentoPDF.open();
            //tamanho do papel
            documentoPDF.setPageSize(PageSize.A4);                     
            //adcionando o logo
            Image imagem = Image.getInstance("C:\\Users\\Admin\\Music\\Dias\\Ministerio da defesa.jpg");
            imagem.setAlignment(1);
            documentoPDF.add(imagem);
            Paragraph m1 = new Paragraph("MINISTÉRIO BRASILEIRO", FontFactory.getFont(FontFactory.TIMES, 12, Font.BOLD));   
            m1.setAlignment(1);
            Paragraph m2 = new Paragraph("EXÉRCITO BRASILEIRO", FontFactory.getFont(FontFactory.TIMES, 12, Font.BOLD));
            m2.setAlignment(1);
            Paragraph m3 = new Paragraph("COMANDO DA 7ª REGIÃO MILITAR", FontFactory.getFont(FontFactory.TIMES, 12, Font.BOLD));
            m3.setAlignment(1);
            Paragraph m4 = new Paragraph("HOSPITAL MILITAR DE ÁREA DE RECIFE", FontFactory.getFont(FontFactory.TIMES, 12, Font.BOLD));
            m4.setAlignment(1);
            Paragraph m5 = new Paragraph("(Hospital Militar de Pernambuco/1817)", FontFactory.getFont(FontFactory.TIMES, 12, Font.BOLD));
            m5.setAlignment(1);
            documentoPDF.add(m1);
            documentoPDF.add(m2);
            documentoPDF.add(m3);
            documentoPDF.add(m4);
            documentoPDF.add(m5);
            Paragraph pularlinha = new Paragraph(" ");
            documentoPDF.add(pularlinha);
            //alinhamento centralizado da imagem
            //criar novo paragrafo  
            Paragraph p = new Paragraph("RELAÇÃO DE APONTAMENTOS REFERENTE AO MÊS "+objDataHora.MostraDataMes()+"", FontFactory.getFont(FontFactory.TIMES, 13, Font.BOLD));
            Paragraph p2 = new Paragraph(" ");
            //alinhamento centralizado do texto
            p.setAlignment(1);
            //cabeçalho do usuario
            Paragraph p5 = new Paragraph("Posto: "+modusu.getPosto()+"", FontFactory.getFont(FontFactory.TIMES, 11, Font.BOLD));
            Paragraph p1 = new Paragraph("Nome: "+modusu.getNome()+"", FontFactory.getFont(FontFactory.TIMES, 11, Font.BOLD));
            Paragraph p3 = new Paragraph("PREC-CP: "+modusu.getPreccp()+"", FontFactory.getFont(FontFactory.TIMES, 11, Font.BOLD));
            Paragraph p4 = new Paragraph("Horário limite para o apontamento: De "+modusu.getHoraEntrada()+" Até "+modusu.getHoraSaida()+".", FontFactory.getFont(FontFactory.TIMES, 11, Font.BOLD));           
            //Tabela de Apontamento
          /*  PdfPTable table = null;
            preenchertab("SELECT*FROM apontamento order by pont_data");
            
            PdfPCell cel1 = new PdfPCell(new Paragraph("Data"));//tabela apontamento
            PdfPCell cel2 = new PdfPCell(new Paragraph("Hora Login"));//tabela login
            PdfPCell cel3 = new PdfPCell(new Paragraph("Hora Apontada"));//tabela apontamento
            PdfPCell cel4 = new PdfPCell(new Paragraph("Justificativa"));//tabela apontamento*/
            
            /*for (ApontamentoLogin pessoa : listp) 
                cel1 = new PdfPCell(new Paragraph(pessoa.getDataAponLog()+""));
                cel2 = new PdfPCell(new Paragraph(pessoa.getHoraLog()));
                cel3 = new PdfPCell(new Paragraph(pessoa.getHoraApont()+""));
                cel4 = new PdfPCell(new Paragraph(pessoa.getJustificativaApont()+"")); */
            
                
          //  documentoPDF.add(p);
          //  p = new Paragraph("  ");
           // documentoPDF.add(p);
            
            documentoPDF.add(p);
            documentoPDF.add(p2);
            documentoPDF.add(p5);
            documentoPDF.add(p1);
            documentoPDF.add(p3);
                documentoPDF.add(p4);
            documentoPDF.close();
            Desktop.getDesktop().open(new File(PDF));
        } catch (Exception e) {
        }       
        
    
        
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Relatorio rela = new Relatorio();
        //rela.setVisible(true);
        jTextFieldPreccpCad2.getText();
        if (enviatext == null) {
                    enviatext = new Relatorio();
                    enviatext.setVisible(true);
                    enviatext.recebendo(jTextFieldRelatorio.getText());
                } else {
                    enviatext.setVisible(true);
                    enviatext.setState(Relatorio.NORMAL);
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldHoraSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoraSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoraSaidaActionPerformed

    private void jTextFieldDgtfamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDgtfamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDgtfamActionPerformed

    
    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonCadasdro;
    private javax.swing.JButton jButtonPreccp;
    private javax.swing.JButton jButtonPreccp1;
    private javax.swing.JButton jButtonRelatorio;
    private javax.swing.JButton jButtonRelatorio2;
    private javax.swing.JComboBox<String> jComboBoxPostocad;
    private javax.swing.JComboBox<String> jComboBoxSexocad;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemADM;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDatausu;
    private javax.swing.JTextField jTextFieldDgtfam;
    private javax.swing.JTextField jTextFieldDgtfamiliar;
    private javax.swing.JTextField jTextFieldHora1;
    private javax.swing.JTextField jTextFieldHora2;
    private javax.swing.JTextField jTextFieldHora3;
    private javax.swing.JTextField jTextFieldHoraLimite1;
    private javax.swing.JTextField jTextFieldHoraLimite2;
    private javax.swing.JTextField jTextFieldHoraSaida;
    private javax.swing.JTextField jTextFieldHoralocalusu;
    private javax.swing.JTextField jTextFieldJustificativa;
    private javax.swing.JTextField jTextFieldNomeCad;
    private javax.swing.JTextField jTextFieldNomeusu;
    private javax.swing.JTextField jTextFieldPostousu;
    private javax.swing.JTextField jTextFieldPreccp;
    private javax.swing.JTextField jTextFieldPreccpCad1;
    private javax.swing.JTextField jTextFieldPreccpCad2;
    private javax.swing.JTextField jTextFieldRelatorio;
    private javax.swing.JTextField jTextFieldSenhaCad;
    private javax.swing.JTextField jTextFieldSetorCad;
    private javax.swing.JTextField jTextFieldhora2;
    private javax.swing.JTextField jTextFieldprec;
    // End of variables declaration//GEN-END:variables

}